Algoritmo "Laço Repetição Para"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Obama
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Lucas Lira
// Data atual  : 04/04/2022
Var
   // Seção de Declarações das variáveis
   contadora:inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para contadora de 1 até 10 passo 1 faca
      Escreval (contadora)
   fimpara


Fimalgoritmo