Algoritmo "Exercicio - A"
// Disciplina : [Lógica de Programação com Javascript]
// Professor : Jailson
// Descrição : o animal ira mostrar o quadrado dos numeros inteiros de 15 ate 200
// Autor(a) : Lucas Lira
// Dados atuais: 07/05/2022
Var
// Seção de Declarações das Variáveis
contadora: inteiro

Inicio
// Seção de Comandos, procedimentos, funções, operadores, etc...
contadora de 15 ate 200 passo 1 faca
escreval(contadora^2)
fimpara

Fimalgoritmo