Algoritmo "Exercicio - C"
// Disciplina : [Lógica de Programação com Javascript]
// Professor : Jailson
// Descrição : o ira mostrar a soma do numero 1 ate 100
// Autor(a) : Lucas Lira
// Dados atuais: 07/05/2022
Var
// Seção de Declarações das Variáveis
contadora,acumuladora: inteiro

Inicio
// Seção de Comandos, procedimentos, funções, operadores, etc...
para contadora de 1 ate 100 passo 1 faca
acomuladora<- acomuladora+contadora
escreval(acumuladora)
fimpara

Fimalgoritmo