Algoritmo "Exercicio - B"
// Disciplina : [Lógica de Programação com Javascript]
// Professor : Jailson
// Descrição : o programa ira demonstrar os numeros pares entre 1 e 500
// Autor(a) : Lucas Lira
// Dados atuais: 16/04/2022
Var
// Seção de Declarações das Variáveis
contadora,par:inteiro

Inicio
// Seção de Comandos, procedimentos, funções, operadores, etc...
contadora<-2
repita
par<-par+2
escreval(par)
contadora<-contadora+2
ate contadora > 500

Fimalgoritmo