Algoritmo "Exercicio - D"
// Disciplina : [Lógica de Programação com Javascript]
// Professor : Jailson
// Descrição : O programa ira acumular o total de grãos
// Autor(a) : Lucas Lira
// Dados atuais: 18/04/2022
Var
// Seção de Declarações das Variáveis
acumuladora,contadora:real

Inicio
// Seção de Comandos, procedimentos, funções, operadores, etc...
contadora<- 1
repita
escreval(acumuladora)
acumuladora<-acumuladora*2+1
contadora<-contadora+1
ate contadora>65
Fimalgoritmo